# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data_transformation.ipynb.

# %% auto 0
__all__ = ['df', 'df_approval', 'calculate_approval_rate']

# %% ../nbs/01_data_transformation.ipynb 2
import pandas as pd

# %% ../nbs/01_data_transformation.ipynb 3
df = pd.read_csv('turma_matricula_docente_filtrados.csv')

# %% ../nbs/01_data_transformation.ipynb 5
def calculate_approval_rate(df: pd.DataFrame) -> pd.DataFrame:
    grouped = df.groupby(['nome_docente', 'nome_componente', 'unidade_responsavel'])

    approval_rates = []

    for (teacher, component, unit), group in grouped:
        count_descricao = group['descricao'].value_counts()
        percentage_descricao = (count_descricao / count_descricao.sum()) * 100

        approval_rates.append({
            'nome_docente': teacher,
            'nome_componente': component,
            'unidade_responsavel': unit,
            'taxa_de_aprovacao': percentage_descricao.to_dict()
        })

    return pd.DataFrame(approval_rates)

# %% ../nbs/01_data_transformation.ipynb 6
df_approval = calculate_approval_rate(df)

# %% ../nbs/01_data_transformation.ipynb 7
df_approval.to_csv('taxa_aprovacao_por_componente.csv')
