# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/professor_cheat_sheet',
                'doc_host': 'https://.github.io',
                'git_url': 'https://github.com//professor_cheat_sheet',
                'lib_path': 'professor_cheat_sheet'},
  'syms': { 'professor_cheat_sheet.pull_data': {},
            'professor_cheat_sheet.solara': { 'professor_cheat_sheet.solara.App': ('solara.html#app', 'professor_cheat_sheet/solara.py'),
                                              'professor_cheat_sheet.solara.PieChart': ( 'solara.html#piechart',
                                                                                         'professor_cheat_sheet/solara.py'),
                                              'professor_cheat_sheet.solara.SelectComponente': ( 'solara.html#selectcomponente',
                                                                                                 'professor_cheat_sheet/solara.py'),
                                              'professor_cheat_sheet.solara.SelectDocente': ( 'solara.html#selectdocente',
                                                                                              'professor_cheat_sheet/solara.py'),
                                              'professor_cheat_sheet.solara.SelectUnidade': ( 'solara.html#selectunidade',
                                                                                              'professor_cheat_sheet/solara.py')}}}
