name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Library
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - uses: fastai/workflows/quarto-ghp@master
